taj-ny/InputActions

CMakeLists.txt, README.md, package.nix, src/CMakeLists.txt, src/config/config.cpp, src/config/config.h, src/gesturerecognizer.cpp, src/gesturerecognizer.h, src/gestures/actions/action.cpp, src/gestures/actions/action.h, src/gestures/actions/command.cpp, src/gestures/actions/command.h, src/gestures/actions/globalshortcut.cpp, src/gestures/actions/globalshortcut.h, src/gestures/actions/keysequence.cpp, src/gestures/actions/keysequence.h, src/gestures/condition.cpp, src/gestures/condition.h, src/gestures/gesture.cpp, src/gestures/gesture.h, src/gestures/holdgesture.cpp, src/gestures/holdgesture.h, src/gestures/pinchgesture.cpp, src/gestures/pinchgesture.h, src/gestures/swipegesture.cpp, src/gestures/swipegesture.h
Closes #3.
- **[Gestures][$Device][$Gesture]**
- **TriggerOneActionOnly** (bool) - Whether to trigger only the first action that satisfies a condition.<br>Default: **false**<br>&nbsp; 
- **[Conditions]** - At least one condition (or 0 if none specified) must be satisfied in order for this gesture to be triggered.
- **[$ConditionId]** (int) - Unique ID for this condition.
- **Negate** (bool) - If true, this condition will be satisfied only when none of its specified properties are.<br>Default: **false**
- **WindowClassRegex** (string) - A regular expression executed on the currently focused window's resource class and resource name. If a match is not found for either, the condition will not be satisfied.<br>Default: **none**
- **WindowState** (enum) - ``Fullscreen``, ``Maximized``. Values …
=> Implement conditions

docs/example_gestures.md, src/libgestures/libgestures/yaml_convert.h
Configuration documentation will be updated in #39.
- Types of *Action.keyboard*, *Condition.negated* and *Condition.window_state* are now lists
=> config: use arrays instead of space-separated values

src/kwin/effect.cpp, src/kwin/effect.h
If the effect was loaded when the configuration file didn't exist, the file watcher wouldn't work.
=> kwin: fix config file watcher

flake.lock, flake.nix
This fixes the nixos-unstable workflow, which was using Plasma 6.2.5 instead of 6.3.
=> flake/inputs/nixpkgs: use nixos-unstable

src/kwin/inputfilter.cpp, src/kwin/inputfilter.h
Two-finger pinch gestures may be at first incorrectly interpreted by libinput as scrolling. Libinput does eventually correctly determine the gesture after a few events, but it doesn't send the GESTURE_PINCH_BEGIN event, which prevents the plugin from handling that gesture.
```
event16  GESTURE_HOLD_BEGIN          +109.982s 2
event16  GESTURE_HOLD_END            +110.007s 2 cancelled
event16  POINTER_SCROLL_FINGER       +110.007s vert -1.31/0.0* horiz -1.58/0.0* (finger)
event16  POINTER_SCROLL_FINGER     2 +110.015s vert 0.00/0.0* horiz 0.00/0.0* (finger)
event16  GESTURE_PINCH_UPDATE        +110.022s 2 -1.47/-1.23 (-1.58/-1.31 unaccelerated)  1.04 @  0.48
event16  GESTURE_PINCH_UPDATE      2 +110.030s 2 -1.47/-0.49 (-1.58/-0.53 unaccelerated)  1.08 @  0.47
event16  GESTURE_PINCH_UPDATE …
```
=> kwin: add workaround for two-finger pinch gesture detection

src/kwin/inputfilter.cpp
This reduces the update frequency for hold gestures from 1000 Hz to 200 Hz, improving accuracy for thresholds and intervals.
=> kwin/inputfilter: switch to precise timer, reduce update frequency for hold gestures

src/libgestures/libgestures/actions/command.cpp
Simply adding *&* to the end of the command won't work for multi-line ones. Commands can freeze the compositor and not even switching to a different tty will work.
=> libgestures/actions/command: execute in a separate thread

src/kwin/impl/kwinwindowinfoprovider.cpp
This was probably broken by Plasma 6.3.
=> kwin/windowinfoprovider: fix maximize state detection

src/kwin/impl/kwininput.cpp, src/kwin/impl/kwininput.h
For unknown reasons, InputRedirection::keyboardModifiersChanged doesn't always get emitted. The workaround is to use InputRedirection::keyStateChanged.
#90
=> kwin/input: fix modifier detection

src/kwin/input/emitter.cpp, src/kwin/input/emitter.h, src/kwin/input/keyboard.cpp, src/libinputactions/input/keyboard.h
This also removes the use of methods marked with ``@internal``.
=> kwin/input/emitter: fix build failure on KWin master

src/kwin/input/pointer.cpp
i forgot to change this too (as always)
=> kwin: don't use internal PointerInputRedirection methods

src/libinputactions/triggers/trigger.cpp, src/libinputactions/triggers/trigger.h
Fixes an issue where gestures would end even if the total delta didn't fit within the specified threshold range.
=> libinputactions/trigger: ensure delta within threshold in Trigger::canEnd

src/CMakeLists.txt, src/libinputactions/handlers/mouse.cpp, src/libinputactions/handlers/mouse.h, src/libinputactions/triggers/trigger.cpp, src/libinputactions/triggers/trigger.h, src/libinputactions/triggers/wheel.cpp, src/libinputactions/triggers/wheel.h, src/libinputactions/yaml_convert.h
Wheel gestures will no longer suddenly work in a completely different way when a modifier or button is present. Now the gesture must have an update action in order for that to happen.
=> libinputactions: make wheel gestures continuous only when an update action is present

src/libinputactions/handlers/mouse.cpp, src/libinputactions/handlers/mouse.h
This should fix mouse gestures with speed behaving not as expected.
=> libinputactions/mouse: don't attempt motion trigger activation if there had been an active trigger since the last key/button press

src/kwin/input/backend.cpp, src/libinputactions/handlers/touchpad.cpp, src/libinputactions/handlers/touchpad.h, src/libinputactions/yaml_convert.h
So it turns out that it is possible to detect the end of scroll gestures by checking for a delta of (0,0), which removes the need to rely on timeouts.
Events with a delta of (0,0) will never be blocked anymore, as this would mess up kinetic scrolling.
Fixes #115
=> libinputactions/touchpad: improve scroll handling

src/kwin/Effect.cpp
If value is not set, the variable becomes empty and a ``== false`` condition is not possible.
=> kwin: fix plasma_overview_active variable

src/libinputactions/handlers/MouseTriggerHandler.cpp, src/libinputactions/handlers/MouseTriggerHandler.h, src/libinputactions/triggers/Trigger.cpp, src/libinputactions/triggers/Trigger.h, src/libinputactions/yaml_convert.h, tests/libinputactions/triggers/TestTrigger.cpp
New property: *Gesture.mouse_buttons_exact_order*
=> libinputactions: allow mouse gestures with specific press order

src/hyprland/Plugin.cpp, src/kwin/Effect.cpp, src/libinputactions/Config.cpp, src/libinputactions/Config.h
Fixes #119 (unless the user deletes the entire directory but I'm not adding logic for that).
Configuration file is now located at ``~/.config/inputactions/config.yaml``, old config (``~/.config/kwingestures.yml``) will be copied to this path automatically once.
Configuration file load order:
- ``~/.config/inputactions/config-debug.yaml`` (debug builds)
- ``~/.config/inputactions/config.yaml``
=> libinputactions/config: move path, fix watcher

src/kwin/README.md
Hello,
I am the maintainer of the AUR package linked in the kwin-README. renamed the AUR package in order to conform to the naming of the official NixOS flake and to make the relation between that package and possible future inputactions-hyprland and inputactions-standalone clearer.
(As a sidenote I looked into creating a PKGBUILD for inputaction-hyprland, but I think using hyprpm is preferable so I didn't)
=> AUR package was renamed

src/kwin/interfaces/KWinInputEmitter.cpp, src/kwin/interfaces/KWinInputEmitter.h, src/kwin/textinput.h, src/libinputactions/actions/InputTriggerAction.cpp, src/libinputactions/actions/InputTriggerAction.h, src/libinputactions/interfaces/InputEmitter.cpp, src/libinputactions/interfaces/InputEmitter.h, src/libinputactions/yaml_convert.h
This makes it possible to write text into input fields of clients that support the Text Input protocol.
```yaml
input:
- keyboard: [ text: "asdasdasd!!!!!" ]
```
KWin only for now and for some reason key events are always handled after text but that's good enough for what I want.
=> {libinputactions,kwin}: add InputEmitter::keyboardText

.github/FUNDING.yml
because github is stupid and displays the sponsor button on repos where i disabled it
=> .github/funding: create

src/libinputactions/actions/CommandAction.cpp, src/libinputactions/actions/CommandAction.h, src/libinputactions/yaml_convert.h
Allows for blocking action execution until the shell exits. Some programs may not work as expected if many instances are launched at once, which can happen if a gesture with a repeating action is performed quickly.
=> libinputactions/actions/command: add wait property

src/libinputactions/input/InputEventHandler.cpp, src/libinputactions/input/InputEventHandler.h, src/libinputactions/yaml_convert.h
Removes *[EventHandler](https://wiki.inputactions.org/v0.7.0/config.html#eventhandler).blacklist* and *whitelist*, see property description for alternative.
=> libinputactions: drop EventHandler.{blacklist,whitelist}

src/libinputactions/actions/CommandAction.cpp
=> libinputactions: don't make QProcess a child of CommandAction

src/libinputactions/handlers/MotionTriggerHandler.cpp, src/libinputactions/handlers/MotionTriggerHandler.h
One is not enough to accurately determine the direction, especially when it comes to mouse gestures.
=> libinputactions/handlers/motion: require >=2 deltas before determining direction

src/kwin/interfaces/KWinInputEmitter.cpp, src/kwin/interfaces/KWinInputEmitter.h, src/libinputactions/actions/InputAction.cpp, src/libinputactions/actions/InputAction.h, src/libinputactions/config/yaml.h, src/libinputactions/interfaces/InputEmitter.h
Couldn't get it to work on Hyprland so KWin only for now.
There will be no actions for moving the wheel by the delta or the distance from the origin (both of which would be useful for autoscrolling gestures), that will be achievable with scripting, which will be added soon.
| Action | Description |
|-|-|
| ``wheel [x] [y]`` | Move the wheel by (*x*, *y*). 
```yaml
input:
- mouse: [ wheel 0 10 ]
```
closes #158
=> libinputactions/actions/input: add mouse wheel
